### ISSUE TITLE
Status of delegated harvesting says "locked" when it is really "unlocked"

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#101]
I have an account TA66MVNSS55QQPS4GUUDNLZJJHLYTTEYS5CIFP26

The delegated harvesting account is TAAD4F-YUOYNX-AXCYBV-5ZDBUD-X4GS2Q-SVAG2K-RLPK

You can see them linked here on Bob. http://bob.nem.ninja:8765/#/search/TA66MVNSS55QQPS4GUUDNLZJJHLYTTEYS5CIFP26

but app says delegated harvesting is locked.

**Comment by fyahfox** [comment]
confirmed

**Comment by am4n0w4r** [comment]
Fixed but can't test without unlocked account.

**Comment by fyahfox** [comment]
not fixed in 0.1.31

if you need a private key of an account that has delegated harvesting unlocked, i can help you

**Comment by am4n0w4r** [comment]
It can't be fixed in 0.1.31 because the issue is created the next day after it was built :)
Thanks, my account have already been unlocked and it shows unlocked status, in 0.1.32;

**Comment by fyahfox** [comment]
sorry, i dont know why i thought you meant fixed for 0.1.31^^
