### ISSUE TITLE
Clicking on "Share QR" freezes tablet for 5 seconds

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#102]
Sometimes the tablet complains that the NEM app is not responding. It doesn't crash and carries on after a bit.

Nexus 7 2013 running Android 6.0.1

**Comment by bluenem** [comment]
Update: If I click on "Share QR" and then "Invoice" the app crashes

**Comment by fyahfox** [comment]
"If I click on "Share QR" and then "Invoice" the app crashes"
-> https://github.com/NewEconomyMovement/NEMAndroidApp/issues/107

**Comment by bluenem** [comment]
It seems like the creation of the QR code for the address is especially resource intensive on my Nexus 7. Sometimes it would not react for over 5 seconds. 
Question: Once the QR is created for an address, why not save and reuse it? It looks like it is being recreated every time it is needed...

**Comment by fyahfox** [comment]
I think the devs should first look why it takes 5 seconds for your device. Something must be wrong since this should NOT be that slow with your hardware (Quad-core 1.5 GHz, 2 gb ram).

**Comment by bluenem** [comment]
This is the same as #112

**Comment by am4n0w4r** [comment]
Please test this in 0.1.34, there were some improvements in the tab view. If this happens again, please tell me if this is related to all share buttons, or just some of them (export account share/my info/invoice). Marking as resolved, for now.

**Comment by fyahfox** [comment]
lets continue to discuss the performance problem in here:
https://github.com/NewEconomyMovement/NEMAndroidApp/issues/112
