### ISSUE TITLE
Scanned invoice, tried to pay it -> "Sending failed! The entity has already past its deadline"

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#103]
0.1.31

I just tried to pay this invoice:
![photo_2016-01-27_19-15-19](https://cloud.githubusercontent.com/assets/6625264/12623400/4ed15108-c52a-11e5-83c2-9c82360d7248.jpg)

It's not easy to scan it, because of the small resolution (https://github.com/NewEconomyMovement/NEMAndroidApp/issues/87), but I was able to scan it and then tried to send the transaction.

I then got this, although the invoice was created only 2 minutes before I scanned it:
![photo_2016-01-27_19-14-20](https://cloud.githubusercontent.com/assets/6625264/12623428/6f0627b4-c52a-11e5-961a-1c83dd9d17ca.jpg)

**Comment by am4n0w4r** [comment]
Are you still able to reproduce this or was it one-time error? Because I had no problems sending it, yesterday or today, and of course, no timestamps are stored in QR code itself, it can't be expired. Invoices are sent like regular transactions, without functional changes. Please try this again using another server, because the error you see is server error, so this may or may not not be related to the app.

**Comment by fyahfox** [comment]
I just tried it again and it worked. Still this should never happen.
I was always using artygeek server. In which cases exactly could this error message come up? What is the server doing wrong to make the app display this!?

**Comment by am4n0w4r** [comment]
It was one of the documented api [response codes](http://bob.nem.ninja/docs/#nemRequestResult), indicates that transaction deadline already passed. I guess it was just one-time network time synchronization issue as it never happened before and shouldn't happen again.

**Comment by gimer** [comment]
> I guess it was just one-time network time synchronization issue as it never happened before and shouldn't happen again.

so what exactly happened?
do you have raw transaction data?

**Comment by am4n0w4r** [comment]
We don't have raw transaction data as there wasn't any reason logging it until now, so we can't say what exactly happened. We'll add transaction logging in the next build, 0.1.32.
If this error ever happens again, please retry sending immediately after 1-2 seconds, and then try to choose another server and repeat again. This may provide some clues.

**Comment by fyahfox** [comment]
I had it again when sending a TX inside conversation view. I used artygeek server. When I switched to another server, the transaction went through.
What is this about? What NIS is artygeek running?

**Comment by am4n0w4r** [comment]
Artygeek was running 0.6.65, updated to 0.6.73

**Comment by fyahfox** [comment]
Ok, I flag this as resolved. Let's see if we can reproduce it.
