### ISSUE TITLE
Add Account -> Scan QR -> go back -> Create -> Crash

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#104]
0.1.31

A friend of mine just expererienced this:
Fresh install of the app -> Add Account -> Scan QR -> go back -> Create -> The app crashes.

This happened a minute ago, you should be able to see the log.

**Comment by am4n0w4r** [comment]
Yes, I saw the reporter. Please retest in 0.1.32, should not happen again.

**Comment by fyahfox** [comment]
fixed
