### ISSUE TITLE
Clicking on camera image in scan mode throws error

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#106]
Clicking the camera image while in scan mode gives me an error. See attachment.

After clicking ok the app continues to run.
![photo_2016-01-27_19-36-39](https://cloud.githubusercontent.com/assets/16922381/12624080/72966f62-c52d-11e5-9a3c-85803c056fd3.jpg)

**Comment by am4n0w4r** [comment]
This is done intentionally, for possibility to report scanner problems.
