### ISSUE TITLE
QR -> Scan view -> Invoice -> Scan View camera frozen

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#107]
0.1.31

When I go to QR -> Scan I see the camera capture image just fine. When I then slide to "Invoice" and go back to "Scan" the camera capture image is frozen. If I go all the way to "My Info" and back to "Scan" it works again.

For others the app crashes when they go to "Invoice" coming from "Scan". This just happened 1 minute ago to a friend of mine, please see your log.

**Comment by am4n0w4r** [comment]
Please test in 0.1.34, reworked the tab views;

**Comment by fyahfox** [comment]
fixed
