### ISSUE TITLE
Create app password: display error message if user tries to set a too short password 

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#108]
0.1.31

just like here: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/46#issuecomment-169606128

"the dots in the password texbox stay red until a length of 6 chars is reached.
although i think that is pretty good, i think if a user still tries to click "ok" an error should be displayed, that the password is too short. this would make it easier to understand imo."

**Comment by am4n0w4r** [comment]
Resolved in 0.1.33;

**Comment by fyahfox** [comment]
Any reason why you only display an exclamation point in this situation but for app export it displays the exclamation point plus the error message?
Please display the error message here as well.

(And also for "change applicatoin password" of course.)

**Comment by am4n0w4r** [comment]
Android shows error message is shown when input is focused. Otherwise only exclamation mark is shown.

**Comment by fyahfox** [comment]
Hm, I see.
How about this: When the user tries to leave focus of the first password textbox, but password is below 6 chars, the error is displayed and focus stays in first password textbox?

Not sure if that was a dirty hack..?

**Comment by am4n0w4r** [comment]
This may be a little annoying for some users when app grabs focus back if they change it. It is possible, but more gentle approach is to allow user to type anything they want, showing that it can be inappropriate (with just red dots), but when they tap "OK", show an error message and switch focus to topmost invalid input so it can be immediately edited. Please see this in 0.1.35

**Comment by fyahfox** [comment]
Ok, I like that idea, thanks!

**Comment by fyahfox** [comment]
just checked on 0.1.35. nice solution! thx
