### ISSUE TITLE
Going to address book crashes app

### ISSUE THREAD

**Issue by kodaxx** [NewEconomyMovement/NEMAndroidApp#109]
I have a huawei nexus 6p. Any time I click on address book tab from any screen, the app crashes. This happens 100% of the time. I don't get any specific messages. It just informs me that the app has crashed, and then exits

**Comment by am4n0w4r** [comment]
Saw this issue in the reporter. Should be fixed in 0.1.32, can't test because not reproducible.

**Comment by fyahfox** [comment]
@kodaxx please review

**Comment by kodaxx** [comment]
Unfortunately it still crashes on my nexus 6p

**Comment by am4n0w4r** [comment]
Can't reproduce this on either device that we have, or Nexus 6p emulator. Please try with 0.1.35, I made few double checks, at least it shouldn't crash anymore.

**Comment by fyahfox** [comment]
@kodaxx can you please check again?

**Comment by kodaxx** [comment]
Will do. And I will report back

**Comment by kodaxx** [comment]
This is fixed
