### ISSUE TITLE
QR scan behaviour 2

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#11]
QR scans the code and then asks to store in address book. It should instead scan and ask if the user wants to store in Address book. Whether yes or no, it should then plug the address into the send transaction with the amount.

**Comment by fyahfox** [comment]
If a user scans an account QR code, he might not always want to add it to the address book, so I agree the app should ask: Add to address book? yes/no

Besides that, maybe the only reason for scanning the account QR code was to add it to the address book, so the app should also ask: Do you want to send a transaction to that account? yes/no

**Comment by am4n0w4r** [comment]
Resolved in 0.1.32, added two options;

**Comment by fyahfox** [comment]
Nice, thanks!

Three little things though:
1) If address is not in address book yet, only check "Add to address book" by default. (It is unlikely that a user wants to send a transaction as well, because invoices are used for this in the first place.)
2) If address is already in address book, don't display first option as checkbox, but just display the info "Already in address book" and then the by default checked "Send Tranaction" as is.
3) If a user choses to add address to address book, please display label and address of just scanned account, so the user has a chance to see what he is adding to his address book at all.

**Comment by am4n0w4r** [comment]
I've looked at iOS version and changed it to look more like iOS. If contact is not in address book, user can edit name and store it. And if contact is present, it asks if user wants to send transaction to that address.

**Comment by fyahfox** [comment]
That sounds really good, thanks! I'm looking forward to test this :)

**Comment by fyahfox** [comment]
Just one minor thing: Could you still display a short info that the scanned contact is already in address book, if that is the case? It could confuse people if they can only scan, but they actually tried to add it to address book (because they forgot they already added it).

**Comment by am4n0w4r** [comment]
Resolved in 0.1.36;

**Comment by fyahfox** [comment]
We had a little misunderstanding here:
I didn't want you to delete the option to be able to send a transaction to a scanned My Info address which is not on the address book yet. I just wanted you to only check the "add to address book" as default.

So with the current change, can you please add a button "Send Transaction" below "Add to address book"? I don't see a reason to drop that feature completely.

**Comment by am4n0w4r** [comment]
It's not easy to add another button because all popups share the same master layout with one action button, but I've added a checkable option to send transaction after adding contact, so user can tick, press "Add" and will be redirected to new transaction after adding contact. 0.1.37

**Comment by fyahfox** [comment]
I'm sory, but I don't like this at all, becaue now we are back to "user cannot send transaction without adding to address book", which is how this discussion started.

With only 1 button, I can't think of a good solution though...

**Comment by am4n0w4r** [comment]
This popup wasn't anywhere in designs or mockups, so it was my own initiative to do it like that. That's why I deleted it in latest versions.
If you want to change it's behavior, I guess it has to be changed in iOS too.

**Comment by am4n0w4r** [comment]
I'm marking this as resolved because iOS version has recently being updated to reflect currently existing Android behavior [here](https://github.com/NewEconomyMovement/NEMiOSApp/issues/198).

**Comment by fyahfox** [comment]
Ok, I guess we have to overwork this some time in the future. No high priority now.
