### ISSUE TITLE
Sending long messages messes up the design

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#110]
![photo_2016-01-30_13-47-26](https://cloud.githubusercontent.com/assets/16922381/12695751/09f47558-c758-11e5-9a56-f5e1ace32d55.jpg)
![photo_2016-01-30_13-47-29](https://cloud.githubusercontent.com/assets/16922381/12695752/09f6337a-c758-11e5-8822-2caab0bf3684.jpg)

**Comment by fyahfox** [comment]
Yeah, these message boxes must have a width limit. And the full message must be displayed, no matter how many lines it will be.

**Comment by am4n0w4r** [comment]
Fixed in 0.1.34;

**Comment by bluenem** [comment]
confirmed fixed in 0.1.34
