### ISSUE TITLE
Sending very long messages causes an exception

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#111]
![photo_2016-01-30_13-48-53](https://cloud.githubusercontent.com/assets/16922381/12695765/520c8614-c758-11e5-9f18-99eb08895337.jpg)

**Comment by am4n0w4r** [comment]
This is server, not app error. In normal conditions there is an error displayed that message is too large;
![screenshot_2016-02-01-16-59-15](https://cloud.githubusercontent.com/assets/7976963/12720829/5b9f334e-c905-11e5-98a3-c504e2054825.png)

**Comment by bluenem** [comment]
If I send a message with 200 characters I get the error message you posted. But if I send a message with 4000 characters I get the server error I posted.

**Comment by am4n0w4r** [comment]
Okay, I can reproduce this with very long message. But all I can do is just hide that exception and show general message that server error has occurred.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.35, hid server errors with general message;

**Comment by fyahfox** [comment]
I don't get it.
If the message is too long, the app should display a warning and NOT try to send that invalid message to NIS. That shouldn't depend on if the message is just a bit too long or way too long...

**Comment by am4n0w4r** [comment]
Fixed in some of earlier builds, max message length is set to 160 bytes.

**Comment by fyahfox** [comment]
Could you please clarify if you are actually trying to send, although the message is too long? Or does the app see the message is too long and therefor doesn't even try to send it?

**Comment by am4n0w4r** [comment]
The app detects that message is too long, shows it in red and doesn't allow it to be sent if too long
