### ISSUE TITLE
Performance Issues Nexus 7

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#112]
Nexus 7 2013, Android 6.0.1

NEM 0.1.32

I made a little video...

[video_2016-01-30_13-29-21.zip](https://github.com/NewEconomyMovement/NEMAndroidApp/files/110792/video_2016-01-30_13-29-21.zip)

**Comment by fyahfox** [comment]
Yeah, that is unacceptable. Devs, can you please look into this problem? Maybe check logs for that phone specifically. It is not a slow phone, so something must be wrong.

**Comment by am4n0w4r** [comment]
Please do this in 0.1.34: In More menu, select the item "Delete log file". Then go to qr view, switch tabs, share, etc. After that, go to scan tab, send report and please comment here the time when you did it. This should provide necessary logs.

**Comment by am4n0w4r** [comment]
Please test in 0.1.34, reworked the tab views, should work faster; Please report if something;

**Comment by bluenem** [comment]
Tested in 0.1.34: Switching between tabs is faster now. Going to scan mode takes less than 2 seconds. Back to invoice from scan happens instantly. Just creating the QR takes up to 20 seconds, that's a bit slow. During that time the app does not repond.

Did as you said. Deleted log and sent report in scan tab, one minute ago, or 10:40 Berlin time...

**Comment by am4n0w4r** [comment]
Ok, thanks!
@bluenem , creating the QR - you mean 20s is the time between view opening and appearing of the QR code?

**Comment by fyahfox** [comment]
Serious performance improvement confirmed for switching between "My Info", "Invoice" and "Scan" tabs.

I cannot reproduce the 20 seconds loading time for creating an invoice QR. On my phone (HTC One X with Android 5.1.1 custom ROM) it takes approx. 1 second.

**Comment by bluenem** [comment]
@am4n0w4r yes

**Comment by am4n0w4r** [comment]
@bluenem does this problem persist on export account screen?

**Comment by bluenem** [comment]
Strangely the QR generation on the export account screen is quicker. But still takes 8 seconds.

**Comment by fyahfox** [comment]
@bluenem @jabo38 
Please check if performance is good with 0.1.36 now.

**Comment by bluenem** [comment]
Still the same problem with 0.1.36

**Comment by am4n0w4r** [comment]
Please try in 0.1.37, changed code creation mechanism and added more logging to clarify where the holdup is.

**Comment by am4n0w4r** [comment]
And please use log report feature in "More" to send device logs after the problem occurs

**Comment by fyahfox** [comment]
@bluenem can you please check again?

**Comment by fyahfox** [comment]
Well, since nobody else seems to experience this performance problem, I guess it is fixed.
