### ISSUE TITLE
Time on unconfirmed transactions is wrong

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#113]
While the tx is unconfirmed, the time is in the future. Upon confirmation it is changed to correct time. See actual time in upper right corner...

![photo_2016-01-30_13-47-26](https://cloud.githubusercontent.com/assets/16922381/12695859/c89b469c-c75a-11e5-87c5-0a4493be3a3f.jpg)

**Comment by fyahfox** [comment]
good catch.
confirmed for 0.1.32

**Comment by am4n0w4r** [comment]
This is true because unconfirmed transactions has no date yet, so the deadline is displayed instead. Now, we can set this to actual date, or change wording, or remove that label at all

**Comment by fyahfox** [comment]
Oh yes, of course, sorry!
I totally missed the "Due to". Actually, I think we can leave it exactly as is^^

**Comment by bluenem** [comment]
Shouldn't it be "Due by" then? "Due to" means because of...? Or maybe just "Due".

**Comment by fyahfox** [comment]
yes, i will fix that in localization file
