### ISSUE TITLE
conversation view doesn't scroll all the way down (size or height wrong?)

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#117]
0.1.32

![photo_2016-01-31_17-58-20](https://cloud.githubusercontent.com/assets/6625264/12703505/dd126228-c844-11e5-8d89-efd2bce3d0d4.jpg)

**Comment by fyahfox** [comment]
another example, even worse:

![photo_2016-02-03_15-29-44](https://cloud.githubusercontent.com/assets/6625264/12785096/fe01f37a-ca8a-11e5-9a28-e5c1fc08b3c3.jpg)

**Comment by am4n0w4r** [comment]
Resolved in 0.1.34;
