### ISSUE TITLE
App crashes when I try to add new contact to Address Book

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#119]
0.1.32

How to reproduce:
Address Book -> Add New Contact -> enter address and click "OK"

I am wondering where to put the label anyways?

**Comment by bluenem** [comment]
confirmed for 0.1.33

**Comment by am4n0w4r** [comment]
Resolved in 0.1.35;

**Comment by fyahfox** [comment]
confirmed fixed
