### ISSUE TITLE
Time is displayed wrong

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#120]
Time is displayed as 16:2, when clicking on the tx it is displayed correctly as 16:02.
![screenshot_2016-02-01-13-29-19](https://cloud.githubusercontent.com/assets/16880923/12718077/6330e292-c8ec-11e5-8f24-a10ca5f6556d.png)

**Comment by am4n0w4r** [comment]
Fixed in 0.1.33
