### ISSUE TITLE
No feedback on first usage when using unfit password

### ISSUE THREAD

**Issue by patmast3r** [NewEconomyMovement/NEMAndroidApp#121]
When i open the app for the first time and try to use a password that doesn't fit the criteria then i don't get any feedback. Nothing happens no matter how often i try. Only when i use a proper password anything will happen. 

Android 5.1.1
0.1.32.b2296

**Comment by am4n0w4r** [comment]
Are you talking about "Set application password" dialog?
The password dots or hint should stay red when password is too short.
Also, added messages there, in 0.1.33;

**Comment by am4n0w4r** [comment]
Commented in #108, that fixes should resolve this too.
