### ISSUE TITLE
Auto select server does not work

### ISSUE THREAD

**Issue by lcharles123** [NewEconomyMovement/NEMAndroidApp#124]
After adding and selecting a custom server, closing the app, waiting for about 5 minutes, opening the app again; it opens in the primary account but the balance does not appear.
If you go to "servers", will see that has no selected server.
I use 1 min update insterval, if has some importance.
Version 0.1.32

**Comment by fyahfox** [comment]
It seems the app starts looking for a server at Dashboard only. It would be smart if the app would check for best server in background while user still types his app password...

**Comment by am4n0w4r** [comment]
Please test in 0.1.34;

**Comment by am4n0w4r** [comment]
Added background server search on login, and small bug fixed, please test in 0.1.35;

**Comment by fyahfox** [comment]
seems to be faster, so i guess the background search works fine :)
