### ISSUE TITLE
App crahses when sending encrypted message to itself

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#126]
0.1.33

When you send a message from an account to the same account and you encrypt the message, the app crashes.

**Comment by bluenem** [comment]
Also: When you send a tx to yourself (unencrypted) a conversation with yourself appears in the dashboard. When you click on that it opens a seemingly random conversation.

**Comment by am4n0w4r** [comment]
Fixed in 0.1.35;
