### ISSUE TITLE
Sending msg to myself creates "ghost" conversation in dashboard

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#127]
When you send a tx to yourself (unencrypted) a conversation with yourself appears in the dashboard. When you click on that it opens a seemingly random conversation.

**Comment by fyahfox** [comment]
0.1.33

confirmed. this leads to strange behaviour.

**Comment by bluenem** [comment]
Did some more testing. It actually doesn't jump to a random conversation but shows all conversations mashed together in one view.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.35;
