### ISSUE TITLE
Notification settings still missing

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#129]
0.1.33

Till now there is only the "Update Interval" in Notifications settings.
On trello/mockup/app report we agreed on more. But to make it simpler, @jabo38 and me agreed on leaving iOS as is right now (iOS itself handels notifications settings for specific apps pretty well) and only updating Android so it has the same functionality.

That is:
Notifications on/off

If on:
Sound/Vibration on/off
Popup on/off
Show notification on lock screen on/off

**Comment by am4n0w4r** [comment]
I talked to iOS developer, it seems like we don't have any popups on iOS, just regular banner notifications, so I'm not sure what popup setting should control.

**Comment by fyahfox** [comment]
Ok, if iOS doesn't have settings for popup on/off, then Android doesn't need it as well. I can't check, because I have no iPhone. @jabo38 ?

**Comment by am4n0w4r** [comment]
Added settings for sound, vibration and showing on lock screen. To hide notification from lock screen, secure lock screen should be enabled and sensitive notifications should be turned off in OS. 0.1.35
