### ISSUE TITLE
Successful scan of QR doesn't auto load keyboard

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#130]
If I am importing an account, I scan a QR, then I am prompted for my password. The cursor is in the password box ready to go but there is no keyboard loaded, so I press the box again to bring the keyboard up.  It really should just be loaded already like it does in other places in the app.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.34;

**Comment by fyahfox** [comment]
fixed
