### ISSUE TITLE
Reimporting of account fails

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#131]
I created a account,I deleted it and tried to reimport it. 
It tells me, "Account already exists"

Error was not reproduceable.
Tested with:
HTC One X
Android 4.2.2

**Comment by am4n0w4r** [comment]
You deleted the account and then instantly moved to importing, without closing accounts screen, right?
Fixed in 0.1.34;

**Comment by Braintecho** [comment]
Right, thanks!
