### ISSUE TITLE
Amount gets repeated when type

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#132]
Using  Samsung phone, the about gets repeated when type. Example:

Typing 15 during a send transaction, the numbers 1515 came out. Then when pressing the back button, another 15 came out making it 151515, before it can start to erase backwards.

Consistent error throughout tests.

**Comment by am4n0w4r** [comment]
Does this happen in 0.1.34?

**Comment by rmtodd618** [comment]
Sorry. I just made an issue on this also. I am using an LG G3 and have the same issue. I am using version 0.1.36.b2565 so yes it is still happening.

**Comment by rmtodd618** [comment]
I created Issue 162 and 163 on this also if you want to read my notes. I didnt see there was a second page for all the bugs until after creating a bunch of issues.
