### ISSUE TITLE
Error message for invalid QR codes

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#136]
0.1.34

I was trying to fix the localization file to make the app display "This is not an account QR" in case a user scans any other QR while trying to import an account.
I noticed that the localization file is maybe not catching these exceptions in a way so I can do that.

Can you explain to me how I can set specific error messages for error cases for wrong QRs?
- Import account -> Scan QR: Scanning a QR that is not an account QR
- QR -> Scan: Scanning a QR that is not Invoice or My Info

**Comment by am4n0w4r** [comment]
I'll add specific messages for this in 0.1.36.
What message should be displayed when user tries to scan QR that is not Invoice or My Info?

**Comment by fyahfox** [comment]
Hmm, actually the best way would be:
- User is in QR -> Scan view and scans an account QR: App asks if user wants to add that account to his wallet
- User is in QR -> Scan view and scans a QR that is non NEM related at all: "This is not a NEM QR code"

**Comment by am4n0w4r** [comment]
When user tries to scan non-compatible QR, app already says "Not a NEM Qr".
The quickest fix to enable account scanning at "QR -> scan" is to just allow it programmatically, it's a very small change.
And account import is asking for password immediately, I'm not sure if we really need to add another dialog asking if user wants to import it? I think they can just cancel password prompt if they don't want to import it, what do you think?

**Comment by fyahfox** [comment]
Hm, you are right. Just allow account importing at QR -> Scan. Thats fine.

But we do need the error message if somebody tries to scan a My Info or Invoice at Create Account -> Scan QR

**Comment by am4n0w4r** [comment]
Please see in 0.1.36, if user tries to scan non-account qr in scan account view, message "This is not an account QR" should be displayed. At QR -> Scan all qr types are now allowed.
