### ISSUE TITLE
Address book -> after new contact added, view is not refreshed

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#137]
0.1.35

When you manually add a new contact to the address book, you get back to the address book view, but the new contact is not there.

**Comment by am4n0w4r** [comment]
Fixed in 0.1.36;

**Comment by fyahfox** [comment]
Did you try to add an address? It tells me "Invalid address"...

**Comment by am4n0w4r** [comment]
Haven't noticed this, it was due to autocomplete changes that were done after address book testing.
Actually it works for me in 0.1.36 but only if address doesn't contain dashes or other invalid symbols. Fixed to normal behavior in 0.1.37;
