### ISSUE TITLE
notification settings are buggy

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#139]
0.1.35

The notification settings have several bugs, please test and fix.

Example: Setting it up for the first time (1 minute, sound on, vibration on, show on secure lock screen off). Go back, go back into options -> show on secure lock screen ON).
Example 2: I set it to 1 minute -> no message. I set it back to never -> message that short update interval should be for testing only.
...

**Comment by am4n0w4r** [comment]
Fixed small initialization bug in 0.1.36, not reproducible anymore;
