### ISSUE TITLE
no notifications on LG G3

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#140]
I haven't ever been able to get notifications on this phone. Running the lastest Android 4.4 and latest NEM version.

**Comment by am4n0w4r** [comment]
Tested on LG L90, G3 and G3 Stylus, all running Android 5.0-5.1, no problems with notifications. We have also Android 4.4+ phones, no problems there, too. Cannot reproduce this.

**Comment by jabo38** [comment]
Hi @am4n0w4r this could be my fault.  I'm not use to Android.  Just got a phone to test this app.  I found out that the notification drop down menu is actually showing transactions.  When I have the phone on and an app going, I can hear a sound and buzz, but when the phones screen is off, I get no buzz or sound.
