### ISSUE TITLE
Need the auto-suggest feature for names and addresses on new transaction

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#141]
This is how it was implemented in iOS.  

![photo_2016-02-10_23-49-54](https://cloud.githubusercontent.com/assets/10395907/12950570/20d8f8e6-d051-11e5-89e0-be97ed1041cb.jpg)

**Comment by am4n0w4r** [comment]
Resolved in 0.1.36;

**Comment by jabo38** [comment]
fixed
