### ISSUE TITLE
LG G3 is now not responsive and very slow

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#142]
Up until recently that app was responsive and worked well.  Now on version 1.35 on Android 4.4 the app is moving really slowly.  A few others in the mobile chat have also complained that the app isn't responsive.  

Here is a video comparing to iOS.  LIke I said, until recently they were basically the same speed.  

https://www.dropbox.com/s/nni6t4ili7ce9e1/Video%20Feb%2011%2C%2012%2000%2047%20AM.mov?dl=0

Also see this video as it is similar I guess.  https://github.com/NewEconomyMovement/NEMAndroidApp/issues/112

**Comment by bluenem** [comment]
Since 0.1.34 I too noticed that the dashboard has slowed down. In earlier versions it was loading instantly, now it takes a bit of time.

**Comment by bluenem** [comment]
That's on my Nexus 7 with Android 6.0.1

**Comment by am4n0w4r** [comment]
There was excessive logging added, it should behave normally, or maybe a little faster, since 0.1.36;

**Comment by jabo38** [comment]
fixed in LG G3
