### ISSUE TITLE
Don't forget half filled textboxes when leaving the app

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#145]
0.1.35

When you leave the iOS app while filling out a transaction (new transaction or conversation view), when you reopen the app, it brings you back to new transaction screen with your half filled textboxes.

Android should do the same.

Of course this wont be possible for hours or days, because Android will clear data in RAM. But there is no reason to just clear it immediately, right?

**Comment by am4n0w4r** [comment]
Fixed in 0.1.39;

**Comment by fyahfox** [comment]
0.1.39

That doesn't work for me. App just goes back to account list and half filled transaction is gone when I go the account and "new transaction" again. How does it work for you?

**Comment by am4n0w4r** [comment]
Please try to open new transaction, fill the fields, then exit the app, after that select the app from recent, and it should open the same new transaction screen after login with same state as it had before closing.

**Comment by fyahfox** [comment]
Ah ok, so this only works when you go back via "recent apps". Does it have to be restricted to this?

**Comment by am4n0w4r** [comment]
No, I removed that restriction in the next build

**Comment by fyahfox** [comment]
very nice, thanks!
