### ISSUE TITLE
Dashboard is very laggy

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#147]
Android 4.2.2
HTC One X
0.1.35
Dashboard is extremely laggy when scrolling, reaction uncontrolled with time delay.

When entering from a different menu back to dashboard it takes up to 3 sec to display it.

**Comment by jabo38** [comment]
sounds pretty similar to this https://github.com/NewEconomyMovement/NEMAndroidApp/issues/142

**Comment by fyahfox** [comment]
and https://github.com/NewEconomyMovement/NEMAndroidApp/issues/112
