### ISSUE TITLE
False Error report when importing priv. key

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#149]
When I imported my private key(as characters), error message shows up:
"failed to create account" "account already exists" 

But it let me import it without trouble, besides the misleading msg.

**Comment by am4n0w4r** [comment]
What do you mean by 

> it let me import it without trouble, besides the misleading msg.

?
Did you end up with two accounts in the list with same private key?

**Comment by Braintecho** [comment]
I mean with this that an error message appeared, without the error happening.

**Comment by am4n0w4r** [comment]
Removed the "failed to create account" redundant message.

**Comment by fyahfox** [comment]
@Braintecho can you confirm this fixed? i can't reproduce it, but that might be because i am not 100 % sure how to reproduce it.

**Comment by Braintecho** [comment]
NCVEVJSXVSEMH7KPKBBMP7EHL3RWG3EYNMPPINMI

**Comment by jabo38** [comment]
bounty paid 
tx a89b89a6a758d8046cba5f70f35f8ea0edc448a17d3beb316f8f6cc23f5e6236
