### ISSUE TITLE
Trying to create multisig crashes app

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#154]
0.1.36:

![screenshot_20160212-104920](https://cloud.githubusercontent.com/assets/16922381/13003599/df5588e0-d176-11e5-9da8-50d17bcd938b.png)

**Comment by bluenem** [comment]
Also: Entering invalid public key throws server error:

![screenshot_20160212-104120](https://cloud.githubusercontent.com/assets/16922381/13003635/111265b0-d177-11e5-91d0-ecd93e09b7d9.png)

**Comment by jabo38** [comment]
@bluenem in the above picture, it looks like you wanted to make the multisig account with 1 account as the parent but set it to 2 signers.  If you only add 1 public key, then the max amount of signers can only be 1, not any number greater than 1.  So we definitely need an error report for that. 

On the second issue, we will also need an error for when there is a wrong plubic key.  Good finds.

**Comment by bluenem** [comment]
Yeah I'm pretty sure I wasn't exactly knowing what I am doing. But then I was just emulating the average user right :)

**Comment by am4n0w4r** [comment]
Resolved in 0.1.38;

**Comment by fyahfox** [comment]
@bluenem can you confirm this fixed?
