### ISSUE TITLE
Display warning when deleting account

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#155]
There should be a popup or something when the user deletes an account, making sure they understand the consequences.

**Comment by rmtodd618** [comment]
There is an undo after you delete it though.

**Comment by jabo38** [comment]
undo acts as a pop-up.  @bluenem if you don't see the undo, please let us know

**Comment by bluenem** [comment]
No I get the undo all fine. It's just quite easy to click it away, even by accident. So in order to save some potential grief I thought there should be a big fat warning in red and all CAPS!!1! But that's just my opinion.
