### ISSUE TITLE
New Transaction -> Manually paste address not working

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#156]
0.1.36

When creating a new transaction and pasting an address it won't work complaining that the address is invalid.

**Comment by bluenem** [comment]
![screenshot_20160212-135303](https://cloud.githubusercontent.com/assets/16922381/13007419/67d09ef8-d190-11e5-9cbe-eec53baefefb.png)

**Comment by am4n0w4r** [comment]
Fixed in 0.1.37
