### ISSUE TITLE
Unable to click on multisig

### ISSUE THREAD

**Issue by rmtodd618** [NewEconomyMovement/NEMAndroidApp#159]
I am unable to get into multisig
![screenshot_2016-02-12-20-10-05](https://cloud.githubusercontent.com/assets/8193467/13025137/ef706ad8-d1c6-11e5-8261-148917cdc5da.png)

version 0.1.36.b2565

**Comment by rmtodd618** [comment]
version 0.1.36.b2565
LG G3
android 5.0.1
kernel version 3.4.0

**Comment by jabo38** [comment]
the account you are trying to make has not made an out going transaction yet.  in NEM to turn an account into a multisig account, it needs to have a known public key to the network.
