### ISSUE TITLE
Map... what is it supposed to do

### ISSUE THREAD

**Issue by rmtodd618** [NewEconomyMovement/NEMAndroidApp#160]
When I open the map it I would assume it would try to locate my zipcode to find my location. Is this a future feature or a possible bug? Its currently not even hovering over the US where I am located.

**Comment by rmtodd618** [comment]
version 0.1.36.b2565
LG G3
android 5.0.1
kernel version 3.4.0

**Comment by jabo38** [comment]
Confirmed on my LG G3.  iOS version of this app does indeed zero in to your exact location.  

@am4n0w4r is there some reason our phones aren't locating the person's location?

**Comment by fyahfox** [comment]
the map is a prepared feature for future use cases. as long as these use cases don't exist, it should be hidden.
@am4n0w4r we talked about this right? please hide the map from the more menu.

**Comment by am4n0w4r** [comment]
Hid the map in 1.0.42.
For centering on current location, we need to request location permissions.
