### ISSUE TITLE
Creating invoice adds extra numbers on amount

### ISSUE THREAD

**Issue by rmtodd618** [NewEconomyMovement/NEMAndroidApp#162]
When I was creating an invoice I typed 1555 and it spit out the screen shot below. After screwing around with it a few times it appears everytime you type a number it adds on what ever was on there before. Example:
Typing 1 works fine
Typing 15 will spit out 115
Typing 158 will spit out 1151158
![screenshot_2016-02-12-20-39-23](https://cloud.githubusercontent.com/assets/8193467/13025276/1cf503f4-d1c9-11e5-98ec-c50ed0a57d66.png)

**Comment by rmtodd618** [comment]
version 0.1.36.b2565
LG G3
android 5.0.1
kernel version 3.4.0

**Comment by am4n0w4r** [comment]
Fixed in 0.1.37, it seems like some phones just ignore input settings;

**Comment by am4n0w4r** [comment]
Does this happen when entering address manually for new address book contact on the same device?

**Comment by rmtodd618** [comment]
I do not have this issue when adding contacts. Strictly in the QR-invoice-amount section

**Comment by am4n0w4r** [comment]
Ok, I see. Is it gone in 0.1.37?

**Comment by rmtodd618** [comment]
where can i get the 0.1.37

**Comment by fyahfox** [comment]
You always find the current version in the original post of this thread:
https://forum.nem.io/t/nem-mobile-app-open-beta-and-10-000-xem-bug-bounty/1825

Please test and confirm if fixed, thanks!

**Comment by fyahfox** [comment]
This is most likely related to #163 and since that was fixed, I'll close this issue too.
