### ISSUE TITLE
Deleting numbers on invoice adds numbers

### ISSUE THREAD

**Issue by rmtodd618** [NewEconomyMovement/NEMAndroidApp#163]
So after trying to add numbers to the amount on creating an invoice I attempted to delete the numbers and when hitting backspace it added numbers. Here is exactly what it did.
So in the amount section the following numbers were there
1111151158
I then hit the backspace on phone and it added 115 to my number on the phone(1111151158115). I then hit it again and it added another 11 (111115115811511)and then again it added a 1(1111151158115111) but after that it finally started to delete the numbers. Very weird but it may have something to do with the other bug I posted. The message field didnt seem to have any issues thought. I added numbers, letters and then also deleted them without an issue so I am assuming it strictly a code issue with the amount section.
I am using an LG G3

**Comment by rmtodd618** [comment]
version 0.1.36.b2565
LG G3
android 5.0.1
kernel version 3.4.0

**Comment by jabo38** [comment]
This is the same bug as reported here https://github.com/NewEconomyMovement/NEMAndroidApp/issues/162

Basically the auto-suggest is turned on and is filling in extra data.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.37
