### ISSUE TITLE
New Transaction: adress line a bit hidden

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#164]
The name of the to be tipped figures is covered a bit, nothing harsh, you just don´t see what it writes there exactly. Could anoy someone.

HTC ONE X
Android 4.2.2
version 0.1.36.b2565

![screenshot_2016-02-17-19-55-27](https://cloud.githubusercontent.com/assets/16880923/13129677/cd915eba-d5de-11e5-8f32-fc0f2c74d05b.png)

**Comment by jabo38** [comment]
So basically he is saying the bottom of the "kau" isn't visible all the way.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.38;
