### ISSUE TITLE
Error: colours in chat gets displayed wrong

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#165]
Normaly, as receiver the text sent to me is displayed in grey,
But here, inmiddle of convo, received text turns from grey to green, like the text that Im supposed to write and it moved to the right side, were normally just my text should stand.
7:02 correctly displayed
20:13 incoming first time displayed in green
20:16 second time
21:37 me answering

HTC ONE X
Android 4.2.2
version 0.1.36.

![screenshot_2016-02-18-01-00-08](https://cloud.githubusercontent.com/assets/16880923/13129830/d5201c2e-d5df-11e5-8768-24e49217113b.png)

**Comment by jabo38** [comment]
closing for now
