### ISSUE TITLE
color of "0 XEM" in Dashbaord

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#171]
0.1.38

I just noticed that the amount of a TX with 0 XEM is displayed gray in the dashboard, but if I scroll down (so its not visible) and back up, it is green or red.

To avoid this, I suggest to just always make it red for outbound and green for inbound transactions.

**Comment by am4n0w4r** [comment]
Fixed in 0.1.39;
