### ISSUE TITLE
missing string for translation "Failed to serialize transaction!"

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#177]
1.0.42

I just tried to send a transaction, and then got this:
"Sending failed! Failed to serialize transaction!"

For the "Failed to serialize transaction!" part I can't find a string to translate in the localization file.

**Comment by am4n0w4r** [comment]
Fixed in 1.0.43, renamed to errormessage_failed_to_prepare_transaction;
