### ISSUE TITLE
creating invoice: account textbox should not be input

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#18]
Creating Invoice: The account name does not require input. Should just be a message. Invoice number is blocked by the keyboard. Anyway to display invoice number input field without being blocked? https://goo.gl/v4pH8W

**Comment by fyahfox** [comment]
fixed. can you confirm?

**Comment by am4n0w4r** [comment]
Fixed in 0.1.20.
