### ISSUE TITLE
v1.0.44.b3017 can't work in my android phone

### ISSUE THREAD

**Issue by kkooii** [NewEconomyMovement/NEMAndroidApp#189]
it's can't send tx. multisig do not work.

**Comment by kkooii** [comment]
android v5.1 ，kernel 3.10.65

**Comment by kkooii** [comment]
android v5.1 ，kernel 3.10.65

**Comment by am4n0w4r** [comment]
@kkooii could you please provide additional information about what happens?

**Comment by kkooii** [comment]
this is about can't send tx
![img_20160330_205425](https://cloud.githubusercontent.com/assets/8058411/14142701/d576e6da-f6b9-11e5-91cd-40f4cb161676.jpg)

**Comment by am4n0w4r** [comment]
@kkooii please test this in v1.0.45, as we added specific error logging in that verision

**Comment by SpiderBTT** [comment]
It's ok now.

**Comment by kkooii** [comment]
in my android phone . create multisig is ok.sending tx is ok.but as a cosigner is not sign a multsig tx because of no tx to sign

**Comment by kkooii** [comment]
in my android phone . create multisig is ok.sending tx is ok.but as a cosigner is not sign a multsig tx because of no tx to sign

**Comment by kkooii** [comment]
in my android phone . create multisig is ok.sending tx is ok.but as a cosigner is not sign a multsig tx because of no tx to sign

**Comment by kkooii** [comment]
in dashboard there is no TXes

**Comment by kkooii** [comment]
in dashboard there is no TXes

**Comment by am4n0w4r** [comment]
> in dashboard there is no TXes
This is another issue. Please close this issue if you think it is resolved, and open another for that.
