### ISSUE TITLE
before creation of invoice is done: let user decide to share or display QR code

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#19]
Instead of putting the "share" after creating the invoice, why not save one step. In the creation of the invoice, you either share it or display a big QR code straight away? See clouded marking here https://goo.gl/oPkPNe        uhm may i comment (mixmaster): we have a design suggestion for this in the redesign pdf... or what are you talking about?

**Comment by fyahfox** [comment]
I personally like the way it is now. First you create the invoice, then you have a chance to look over it again to be very sure and then you can share it or let somebody scan, whatever you like.
This one click is not a problem imo.
