### ISSUE TITLE
Transactions to myself show as outgoing transactions

### ISSUE THREAD

**Issue by nemster** [NewEconomyMovement/NEMAndroidApp#192]
Transactions from me to myself are shown with negative amount as if they were outgoing.

We better use a diferent symbol from - , something that represents both outgoing and incoming at the same time.

**Comment by jabo38** [comment]
good point.  NCC uses "±" basically a plus and minus at the same time.

**Comment by am4n0w4r** [comment]
Resolved in 1.0.47;

**Comment by nemster** [comment]
My address is NC6AU7-H2N7VT-AGUL4S-FVS5ZV-NWJKV4-E4B64U-FAUA
Thank you

**Comment by fyahfox** [comment]
nice, please fix for unconfirmed as well.

**Comment by jabo38** [comment]
Transaction hash: 9a3a409c190553e374ab473eadf3bd0205f8584522ae3faa07c3ca975f07969d
Bounty paid.

**Comment by am4n0w4r** [comment]
Fixed for unconfirmed, in 1.0.49;
