### ISSUE TITLE
Unconfirmed multisig transaction details not shown.

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#196]
We should be able to slide a transaction in unconfirmed and see how many people have signed or not signed.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/14230421/898e2a28-f991-11e5-80ed-158af3284851.png)

**Comment by am4n0w4r** [comment]
Added multisig transaction info for multisig account, in 1.0.47;
