### ISSUE TITLE
Language file incorrect path Iphone 6 IOS 9.3.1

### ISSUE THREAD

**Issue by kauppalahti** [NewEconomyMovement/NEMAndroidApp#201]
Lithuanian language file follow system language.

![lithuanian 1](https://cloud.githubusercontent.com/assets/6757822/14402061/6f302ae8-fe30-11e5-9a78-141e66834722.png)
![lithuanian 2](https://cloud.githubusercontent.com/assets/6757822/14402062/740ec682-fe30-11e5-91e7-5590a857bfcd.png)

Kauppalahti:
NDNFA5YO3VS2TUQYBILQDORS6IXBCXOOHFWARO4W

**Comment by fyahfox** [comment]
Was that invalid or why did you close it?

**Comment by jabo38** [comment]
Paid here. https://github.com/NewEconomyMovement/NEMiOSApp/issues/195
