### ISSUE TITLE
Keyboard stays opened when it should be closed

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#203]
many times when I am in the app, the keyboard stays open when it shouldn't.  

this happens when I am in a panel that doesn't need a keyboard, like say scan QR to add to address book.  That panel never needs a keyboard.  I leave the phone open on that panel and the phone goes into sleep mode automatically.  I wake the phone and try to open the app.  To open it I am prompted to enter my password and the key board pops up.  I enter my password and enter the app, and land back at the scan QR panel, but.... the keyboard doesn't close.  It is still open.  

LG G3, Android 4.4, NEM version 1.0.47

**Comment by am4n0w4r** [comment]
Forced keyboard hide, in 1.0.48;
