### ISSUE TITLE
Create new contact....keyboard issue.

### ISSUE THREAD

**Issue by appolloburning** [NewEconomyMovement/NEMAndroidApp#204]
Just started testing the app.Testnet #16 - Samsung Galaxy S6, Android 6.0.1
When I open the address book there is a nice big 'add new contact button' which opens a dialogue box with 'name' and 'address' fields.
When typing in the address book each key press after the first combines the previous key presses with the new one.
eg: If i try to type '123456789' it inputs as '112123123412345123456123456712345678123456789' and so forth.
Then when pressing the back space it inputs the last set of data but removes the final entry
eg: '112123' (backspace) '11212312' (backspace) 112123121......and then starts to delete the data.

appolloburning
NDDWK6-FGZBMT-UEIYOO-NKTFFW-EDTV2K-FR2HGZ-UOHM

**Comment by appolloburning** [comment]
Tested on 1.0.48.....issue still occurs.

**Comment by jabo38** [comment]
tx hash: e18145a74e04c1d6f2a0905e2b5401ef23bdb64a0fc02a52d78b92db15cbfe39
bounty paid

**Comment by appolloburning** [comment]
Thanks Jabo,
As per Tolstoys post on the forum, the bug seems to be related to the predictive text function on the Samsung keyboard.
Switching it off removes the problem, but doesn't solve it.

**Comment by fyahfox** [comment]
What irritates me is that no other app seems to have this problem. Something must be wrong then... right?

**Comment by am4n0w4r** [comment]
Fixed, please test in 1.0.49;

**Comment by fyahfox** [comment]
@appolloburning can you confirm this fixed?

**Comment by appolloburning** [comment]
Will test on 1.0.49 tonight.

**Comment by appolloburning** [comment]
Fix confirmed. No further issue.

**Comment by fyahfox** [comment]
thx!
