### ISSUE TITLE
Issue in address input method

### ISSUE THREAD

**Issue by lcharles123** [NewEconomyMovement/NEMAndroidApp#207]
In _New transaction_, if you add a address from drop down menu, try to type something and then erase what was typed, it gives error _Invalid address_ when sending.

**Comment by fyahfox** [comment]
confirmed

**Comment by am4n0w4r** [comment]
fixed. Now when you type something after selecting address, selected value will be reverted to normal address instead of name/address, in 1.0.49

**Comment by lcharles123** [comment]
Here's my address for bounty, thanks!
`NCE4HE7D24R3BF5IO5OZVS4C2D6KUUEW7V4RJ5UZ`

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 41fa867bd8c6fb2ee52a82c913f020c53faa9cdb98cd3083b8ffe16e0fa735dc
