### ISSUE TITLE
Account QR code: There is no feature to export this (as for invoice QR)

### ISSUE THREAD

**Issue by Xpedite** [NewEconomyMovement/NEMAndroidApp#24]
Suggestion for enhancement: 
In the invoice page there is a feature for exporting a QR code (which is really nice ^ ^).
However, for the user info page, the general QR code can not be exported although this would be a useful feature.

**Comment by fyahfox** [comment]
I don't understand what you want to export...

**Comment by Xpedite** [comment]
Well , if you are in the invoice page and create a QR code, there is a button "SHARE" ( by which I mean exported ) but if you look at the general QR code (USER INFO page) for the account there is no button to share the QR code.

**Comment by Xpedite** [comment]
Oeps

**Comment by Xpedite** [comment]
Well , if you are in the invoice page and create a QR code, there is a button "SHARE" ( by which I mean exported ) but if you look at the general QR code (USER INFO page) for the account there is no button to share the QR code.

**Comment by fyahfox** [comment]
Ah ok, yes I think that is planned for the UI overwork.

**Comment by fyahfox** [comment]
fixed
