### ISSUE TITLE
QR Scan not working

### ISSUE THREAD

**Issue by patmast3r** [NewEconomyMovement/NEMAndroidApp#27]
I tried to scan a QR code in an existing account and also to add a new account via qr code but it doesn't work. The camera is activated, i point it at the qr code but nothing is a happening. Like it doesn't seem to recognize that there is a QR code right there. 

Android 5.1.1

**Comment by patmast3r** [comment]
Okay, so when I shot it any random qr code it will tell me that that's not a NEM QR-code. When I show it a NEM QR-code (from a screenshot of the app) it behaves incorrectly as described above.

**Comment by fyahfox** [comment]
I sometimes experience this as well (Android 4.2.2). When I close QR scan and open it again, it often works. I can't figure out in which cases it works and in which not.

**Comment by patmast3r** [comment]
It does seem to work with qr codes that the app provides me. Maybe i got an incorrect qr code. I tried it with this first (which didn't work): https://www.dropbox.com/s/mm481tmy6zb0f6m/jabo8%20yes.png?dl=0

**Comment by am4n0w4r** [comment]
Resolved in 0.1.24.
Cross-platform qr scan now should work.

**Comment by lcharles123** [comment]
Scan works from Android qr, but sometimes the app stops when shows the request screen.
iOS qr crashes the app without showing anything.

Version 0.1.24

**Comment by fyahfox** [comment]
the original issue was fixed, but cross-platform QR scan does not work, I will create a new issue for that.

**Comment by fyahfox** [comment]
not workig in v0.1.26 again

**Comment by am4n0w4r** [comment]
As this is one hard to catch bug, I've added possibility to send report if QR scanner doesn't want to work, in v0.1.27. Now, if you encounter that it's not focusing, or doesn't see the code, just tap on camera preview and agree to send report. Than we'll be able to investigate what component is failing. Please do this as soon as possible after scanner started so essential initialization logs won't be overwritten with per-frame debug info.

**Comment by lcharles123** [comment]
I can't scan nothing, although the camera focuses. No errors occurs.
Version 1.2.7.b1956

**Comment by fyahfox** [comment]
still not working on 0.1.29

**Comment by am4n0w4r** [comment]
Please test this in 0.1.30, fixed weird bug in QR scanner that was due to inconsistent and undocumented Android realizations.
