### ISSUE TITLE
0 is an invalid amount

### ISSUE THREAD

**Issue by patmast3r** [NewEconomyMovement/NEMAndroidApp#29]
When creating a tx the app first says 0 is an incorrect amount but then when I change it back to 0 in the second step (no idea what that step is for in the first palce) it works. 
0 should never be an invalid amount since that's what people will use if they just send messages.

**Comment by am4n0w4r** [comment]
Fixed, will be delivered in the next release.

**Comment by am4n0w4r** [comment]
Since 0.1.23 all amount inputs should allow zero as valid, when it's applicable.
