### ISSUE TITLE
Wording when sending transaction

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#30]
0.1.20.b506

When you send a transaction the app displays a popup message telling that it was "announced". I think a more mainstream friendly wording should be used.
Maybe: Your transaction was sent!

**Comment by am4n0w4r** [comment]
Changed to "Transaction sent". Looks short and descriptive. Also changed "Anouncing..." to "Sending...". Will arrive in v0.1.21.

**Comment by fyahfox** [comment]
very good
