### ISSUE TITLE
Displaying unconfirmed transactions

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#31]
0.1.20.b506

When unconfirmed transactions are available, the app displays a popup message asking if it should be displayed.
This is very inconvenient. Unconfirmed transactions should just be displayed like usual transactions, but they should be flagged "unconfirmed" (clearly visible).

**Comment by patmast3r** [comment]
Absolutely agree!

**Comment by fyahfox** [comment]
v0.1.24.b1495

Now unconfirmed transactions are not displayed at all. This is better then before, but I'm not sure if this is the way to go / what we agreed on.

**Comment by fyahfox** [comment]
v0.1.29
They now show up as "unconfirmed" inside "message view mode" of the transactions.
I'm fine with that.
