### ISSUE TITLE
Errors for new account QR 

### ISSUE THREAD

**Issue by Xpedite** [NewEconomyMovement/NEMAndroidApp#33]
When in the ADD NEW ACCOUNT  menu, the QR button is used, it directs to the QR IMPORT page. 
This page has the menu header with 'messages', 'scan QR', 'Invoice', and 'user info'. 
When pushing any of these buttons ( except 'scan QR' an error occurs). 
This is probably caused by the fact that there is no use case for these buttons in this menu. 
In fact, only the scan QR code makes sense so it would be better to immediately redirect the on button press event (for the QR button in the ADD NEW ACCOUNT menu ) to scan a QR code to import an account to the contacts. 

I hope this is clear if not , feel free to ask for clarification.

**Comment by fyahfox** [comment]
confirmed

**Comment by am4n0w4r** [comment]
I guess this is not valid after redesign.

**Comment by fyahfox** [comment]
correct, thanks
