### ISSUE TITLE
Cannot generate invoice

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#34]
Message:

Application encountered and logged an unrecoverable error and needs to close.

**Comment by Xpedite** [comment]
I have no issues creating invoices on both my devices.

**Comment by am4n0w4r** [comment]
Does this happen on the same device the #10 happens?

**Comment by am4n0w4r** [comment]
Can this be confirmed on 0.1.24, or closed?

**Comment by lcharles123** [comment]
Creating is working for mine, scanning also works but the app stops when shows the request screen.

**Comment by fyahfox** [comment]
@bluefin18 ?

**Comment by bluefin18** [comment]
THe latest version does not allow prefix and suffix to be tested. Before, it cannot be done with prefix or suffix and creates an error.

**Comment by am4n0w4r** [comment]
v0.1.27 will have default invoice message setting, please test.

**Comment by bluefin18** [comment]
Invoice suffix and prefix seems fine. It is place at the end of the message. Can we place it at the beginning of the message, followed by a colon like the following:

Prefix/1/Suffix: Message here.

Unable to test the scanned QR to see how it looks like as it is not working. By right, the sender on scanning the QR should have the Invoice in the return payment message and the amount automatically put in. When it is sent off, the message should be encrypted.

**Comment by am4n0w4r** [comment]
Changed message format to suggested, in 0.1.29. Please close if you can see generated QR, without errors

**Comment by fyahfox** [comment]
@bluefin18 please report back if you are happy with how it works now

**Comment by bluefin18** [comment]
Passed test. Working now.
