### ISSUE TITLE
When Android scans iOS QR invoices, the balance needs an extra 000000

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#36]
iOS can scan iOS balances just fine.  when android and iOS scan each other there there is a decimal point problem.  explained more here https://github.com/NewEconomyMovement/NEMiOSApp/issues/20

**Comment by am4n0w4r** [comment]
Android version uses the same format as in docs (integer, in micro Xems), i rechecked this. Maybe the problem is in iOS version, I notified iOS developer.

**Comment by fyahfox** [comment]
please open an issue in for iOS (https://github.com/NewEconomyMovement/NEMiOSApp/issues) and not for Andoird if this error is still there.
