### ISSUE TITLE
Display app version at splash screen

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#37]
We had this before, but it doesn't display it any longer on Android v0.1.23.

**Comment by am4n0w4r** [comment]
In 0.1.24 it can be found at More -> About.
Is this ok, or add it to splash too?

**Comment by fyahfox** [comment]
Ah no, that is perfectly fine. It was just nowhere in v0.1.23, thats why I was wondering.
