### ISSUE TITLE
Accounts and Servers -> Edit doesn't work

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#38]
v0.1.23

When I am at the Servers list and I click on "Edit" there is the "edit" with the pencil icon on the left. When I click on that, nothing happens.

I also think the pencil only is enough, the word "edit" is not needed and takes too much space. Or what do you think about this?

**Comment by fyahfox** [comment]
still present in v0.1.24.b1495

**Comment by fyahfox** [comment]
This is also true for accounts, so I updated the headline for this issue.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30;
