### ISSUE TITLE
Servers -> Radio button malfunction

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#39]
v0.1.23

In the server list the radio buttons are all empty. The one which is selected should be filled out.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.25, selected server should be marked green, as in design;

**Comment by fyahfox** [comment]
Thanks, thats a lot better.
Although I would prefer a "normal" behaviour of the radio buttins. Meaning: The non-selected is empty, the selected is filled. I don't care too much about the color for the radio button, but that is the general logic of radio buttons, right?

**Comment by fyahfox** [comment]
Hm, it is weird.
On iOs you cant select a server that is not responding (good!), on Android I can select it. When I then go back to configuration view, and back into servers, artygeek is selected again.

So the question is, did it never switch to that non-working server? If so, why does the GUI appear as if it did?

**Comment by fyahfox** [comment]
I just fired up a local testnet node and added that local IP as a server in the app. I was able to select that and the app is now using that node. But now I cannot switch back to artygeek.

When I shut down my local node, the app automatically switched back to artygeek - so there really IS a fallback? I didn't read anywhere that this is implemented now. Very nice, but it would be good to know, so we can test :)

**Comment by am4n0w4r** [comment]
Yes, there is fallback, server is auto-choosed by checking fastest successful heartbeat response time. We didn't mention this in release because this works in general but during development we've found that it has some issues and doesn't always work as expected.

**Comment by fyahfox** [comment]
I see. You might want to open a new issue for that, so we can discuss some details?

**Comment by fyahfox** [comment]
radio button is fixed
fallback issues here: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/69
