### ISSUE TITLE
Dashboard -> don't show balance if NIS not available

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#40]
v0.1.23

If NIS is not available, it should not display the dashboard headline like this:
#walletname# Error XEM

In this case the balance should just not be displayed at all.

And after this happened and NIS is available again, the balance is red. This will probably be sorted out when you remove the "Error XEM", but I wanted to report to be sure.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.25

**Comment by fyahfox** [comment]
I can't check because there seems to be an auto fall back to a working server now?

**Comment by fyahfox** [comment]
ok i deleted all other servers to check it, balance is gone. thanks :)
