### ISSUE TITLE
Export Account: short password issue

### ISSUE THREAD

**Issue by lcharles123** [NewEconomyMovement/NEMAndroidApp#46]
When I try to export account inserting a password less than 6 characters, the app does not show both error as qr code image.

**Comment by fyahfox** [comment]
Confirmed for v0.1.24.b1495

The app doesn't show an error message but the export just doesnt happen.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.26

**Comment by fyahfox** [comment]
the dots in the password texbox stay red until a length of 6 chars is reached.
although i think that is pretty good, i think if a user still tries to click "ok" an error should be displayed, that the password is too short. this would make it easier to understand imo.
