### ISSUE TITLE
Back button crashes the app in some cases

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#51]
v0.1.24.b1495

When I am in the Dashboard and then click on QR and very fast click back (maybe even before the page is fully loaded), the app crashes. This is also the case when I do the same but with address book or more menu instead of QR, but you have to be even faster.

**Comment by am4n0w4r** [comment]
Couldn't reproduce this on any existing device, please test in 0.1.26, there is some window handling improvements

**Comment by fyahfox** [comment]
hm, thats strange. im pretty sure other people had this problem, too.
i am using a HTC One X btw.

**Comment by patmast3r** [comment]
I can reproduce the issue on Android 5.1.1 (12.1 Cyanogen OPO)

**Comment by bluefin18** [comment]
No problems with Android version 5.02. Using 0.1.26 app version.

**Comment by fyahfox** [comment]
I can't reproduce this issue with 0.1.25.b1662
-> closed
