### ISSUE TITLE
Send Transaction: Default/lowest fee is not displayed

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#52]
v0.1.24.b1495

The "New Transaction" screen displays "Enter Fee" in the fee textbox.
As soon as the user enters an amount, the minimum fee should be calculated and it should be displayed in the fee textbox. Maybe add a (minimum fee) behind, so people understand whats up. But right now it is just confusing for new users.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.26
