### ISSUE TITLE
Address book sorting

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#53]
v0.1.24.b1495

No matter which solution we will finally use (https://github.com/NewEconomyMovement/NEMAndroidApp/issues/21), the sorting should be:
NEM contacts A->Z
other contacts A->Z

Right now I don't even understand which concept is used for sorting. Some contacts are even displayed more than once. No idea what happens here.

**Comment by am4n0w4r** [comment]
Contact sorting is now alphabetical, resolved in 0.1.25
