### ISSUE TITLE
Scrolling when keyboard is displayed

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#56]
v0.1.24.b1495

When the keyboard is displayed the content doesn't scroll in the remaining space. "New Transaction" screen is one example.

**Comment by fyahfox** [comment]
although this is not a mustfix, i wonder if this is a lot of work or not? because it really feels clumsy and i dont see this behaviour in professional apps...

**Comment by fyahfox** [comment]
any comments?

**Comment by fyahfox** [comment]
i just changed this to "mustfix" because it leads to some serious problems where people cant access buttons etc.

**Comment by jabo38** [comment]
For instance on my LG G3, I want to test editing the minimum number of cosigners, but I can't because the keyboard stays open and I can't scroll to the "confirm" button.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30

**Comment by fyahfox** [comment]
When the keyboard is displayed, the "Send" button is cut off at "New transaction". Not a major problem, but it always feels like there might be something that is not accessible if this happens. So it would be nice, if it was possible to scroll enough to see the full button (on all screens where this applies).

Maybe this is connected: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/90

![photo_2016-01-24_14-17-15](https://cloud.githubusercontent.com/assets/6625264/12536444/9c705e2c-c2a5-11e5-9eb9-270ed4d656f9.jpg)

**Comment by am4n0w4r** [comment]
Fixed new transaction layout, added scrolling to create invoice, in 0.1.31;

**Comment by fyahfox** [comment]
Just for the record: There might be a lot of other screens where scrolling need to be working with enabled keyboard. Can you check it by yourself or do we have to make a list for you?

**Comment by fyahfox** [comment]
"New Transaction" and "Create Invoice" screen: I can't scroll at all if the keyboard is up.

"My Info" (QR) screen: When i click on "edit", a popup is displayed and the keyboard is displayed. If I am done writing and click "Ok" or close the popup (cancel) the keyboard doesn't disappear (which it should). But even if the keyboard stays, I can't scroll again.

Same scrolling issue inside "conversation" view (click in Amount or Message textbox).. At least the textbox is cut off. Again: Scrolling should always be possible if keyboard is up.

**Comment by am4n0w4r** [comment]
On New transaction and similar views:
When user taps on any text input, keyboard is shown and focused input should be scrolled right above the keyboard. Then, user have to use next button to navigate between other inputs, the OS will scroll to desired input automatically if this is needed.
After all inputs are filled, "Next" button gets replaced with "Done" which closes the keyboard revealing the whole screen.
This is one keyboard operation mode.
The others are: 1) keyboard pushes all content above itself (including bottom bar). 2) Keyboard just overlays content. All inputs beneath it are not visible.
These are all available options without using hacks.
The easiest way would be to use the "1)" mode and just hide the bottom bar, but Android has no official way to know when the keyboard is displayed/hidden. This is possible to implement using hacks but needs additional time and will likely lead to bugs and drawbacks.

**Comment by fyahfox** [comment]
Thanks for the detailed explanation.
I see. So, this is a problem. Imagine somebody with a small screen: If the keyboard is displayed and the icon bar as well, then there is like nothing left for the actual content.

How much work is it to make the top green bar with less height and the icon bar with less height as well (see iOS, it is better there)?

**Comment by am4n0w4r** [comment]
Please see in 0.1.33;

**Comment by fyahfox** [comment]
So what did you do now?

I see that I can scroll the content while the keyboard is displayed, but the icon bar is not displayed.

Is that a hack now and you expect bugs?

**Comment by am4n0w4r** [comment]
Yes, content should be fully scrollable, with icon bar hidden when keyboard shown, and showed back when keyboard hide itself. It's a hack that generally should work but may have side effects on some devices. Please report if you encounter any.

**Comment by fyahfox** [comment]
Ok, let's keep this open, because this should be tested detailed. Thanks so far.

**Comment by fyahfox** [comment]
I didn't experience any problems with scrolling and didn't hear from somebody else that there is a problem, so I will close this now.
