### ISSUE TITLE
"Invalid amount" tooltip doesn't disappear when switching to scan view

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#57]
v0.1.24.b1495

When I go to QR -> Invoice -> and I click create without entering an amount, a tooltip "Invalid amount" is displayed (which is totally fine of course). When I now go to the "Scan" view, the tooltip does not disappear.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.26

**Comment by fyahfox** [comment]
ok the tooltip is gone completely and "Amount" is red only.
fine with me :)
