### ISSUE TITLE
app sometimes crashes after start

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#62]
v0.1.25.b1662
The app sometimes crashes immediately after I start it.

You should see it in your logs. Example: 2015-12-22 ~10:30 am (UTC+1)

**Comment by lcharles123** [comment]
This happens specifically after going to the home phone screen after logging into the app and return again to it through "recent apps"

**Comment by fyahfox** [comment]
confirmed! good catch

**Comment by am4n0w4r** [comment]
Most of the crashes were related to leaked dialog windows, which differs on some phones, should not happen anymore in 0.1.26, please test
