### ISSUE TITLE
can't send XEM - no error message

### ISSUE THREAD

**Issue by patmast3r** [NewEconomyMovement/NEMAndroidApp#64]
I'm on android 5.1.1 (cyanogen 12.1)

When i try to send XEM back to an address that has sent me XEM I get the message that it was sent but the receiver never gets anything and it also never shows up in my account.

**Comment by am4n0w4r** [comment]
Couldn't reproduce this with any combination of amount/message/encryption - transactions are sent and appear as unconfirmed immediately.
Please test in 0.1.26, and if it still doesn't work, please provide some details to reproduce this, a screenshot would be perfect

**Comment by am4n0w4r** [comment]
There was an issue related to #68, it is fixed, should resolve this too, in 0.1.28;

**Comment by fyahfox** [comment]
@patmast3r I don't know how you produced the error, so please try to reproduce and close, if fixed.

**Comment by patmast3r** [comment]
Issue seems fixed in latest version.
