### ISSUE TITLE
"Harvest Details" issues

### ISSUE THREAD

**Issue by lcharles123** [NewEconomyMovement/NEMAndroidApp#65]
Harvested Blocks don't show correct timestamps and blocks.
https://i.imgur.com/cicbJyT.jpg
It also shows wrong blocks, I was connected to a node with delay, after restarting it and re downloading the blockchain, the app kept showing the blocks that I had not harvested, there is no way to update the list of blocks?

**Comment by fyahfox** [comment]
100% sure you didn't harvest these blocks? did you double check with NCC testnet or testnet block explorer?

**Comment by lcharles123** [comment]
I have checked with NCC, i don't have harvested none between the interval 216653 - 218121
Acc
TDSUBW-KBLTQX-6KAWNY-X5QOXS-BQV2XN-JSMRTS-6SS4

**Comment by am4n0w4r** [comment]
Timestamps fixed, forgot to add Nemesis block timestamp in calculations. Harvested blocks are shown from "/account/harvests" request and it actually returns some blocks. Cannot verify this in NCC, don't have private key for this account.
Is this correct request to display harvested blocks?
http://artygeek.net:7890/account/harvests?address=TDSUBWKBLTQX6KAWNYX5QOXSBQV2XNJSMRTS6SS4

**Comment by lcharles123** [comment]
Yes, are shown correctly now, the error only happened after been connected to a node with delay.

**Comment by am4n0w4r** [comment]
Ok, so I'm marking it resolved, will appear in 0.1.26.

**Comment by fyahfox** [comment]
@lcharles123 can you confirm this is fixed now?

**Comment by lcharles123** [comment]
Yes, timestamps was resolved.
