### ISSUE TITLE
Enter password: dots stay red after wrong password

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#66]
0.1.26.b1876

when i enter a wrong password, the dots in the password-textbox turn red (good).
but it doesnt turn black again when i change the password (delete completely/parts or add something).

**Comment by am4n0w4r** [comment]
Resolved in 0.1.27

**Comment by fyahfox** [comment]
not resolved in v0.1.27.b1956

**Comment by am4n0w4r** [comment]
Was this a login screen issue?
The same error was fixed for change password dialog, now it's fixed for login screen too, 0.1.28;

**Comment by fyahfox** [comment]
oh sorry, i forgot to mention that detail. yes i was talking about the login screen!
thx!
