### ISSUE TITLE
amount of transaction can not have > 6 decimal places

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#67]
v0.1.27.b1956

when i try to send a transaction with an amount which has more than 6 decimal places, the app accepts that. but more than 6 decimal places dont work with NEM.

please block more than 6 decimal places in the amount box (and anywhere where it is possible to set an amount to be sent, like invoice).

**Comment by am4n0w4r** [comment]
resolved in 0.1.28;
