### ISSUE TITLE
Send transaction with zero balance

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#68]
v0.1.27.b1956

It is possible to send a transaction for an account which has a balance of zero.
It seems this leads to weird behaviour after that is done.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.28

**Comment by fyahfox** [comment]
It now says:
Sending failed!
FAILURE_INSUFFICIENT_BALANC
E

Could you make that a bit nicer?^^
What about:
"Sending failed!
Insufficient funds"

**Comment by am4n0w4r** [comment]
Changed text in 0.1.30;
