### ISSUE TITLE
server fallback

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#69]
v0.1.27.b1956

i wonder how this feature works in detail now. maybe the devs can provide some details so we know how to test it?

**Comment by am4n0w4r** [comment]
When app starts, best server is selected from list, based on fastest heartbeat response. User can override selected server but it will eventually be refreshed.

**Comment by fyahfox** [comment]
is it just pinging the whole server list? how often each? or just once?
only at start? or at some other point again?

**Comment by am4n0w4r** [comment]
When app needs to make server request, it checks if it has selected server. And if not, it will [heartbeat](http://bob.nem.ninja/docs/#heart-beat-request) all servers. The first which responds successfully will be selected and used for rest requests. After some time or when app restarts, it will be reselected. If no servers available, then it's not possible to make a request.

**Comment by fyahfox** [comment]
so everytime a request is sent (checking for new TXes e.g.) ALL servers get a heartbeat request?

**Comment by am4n0w4r** [comment]
No, this isn't necessary. Selected server remains valid for some time.

**Comment by fyahfox** [comment]
Sorry to ask again, but how long is "some time"?

**Comment by am4n0w4r** [comment]
Current is set to 20s and can be changed to any value

**Comment by fyahfox** [comment]
ok, we will discuss this internally and get back to you, thanks for the information!

**Comment by fyahfox** [comment]
alright, please change 20s to 300s (5 minutes).

and please make sure the heartbeat check is triggered again in case the currently selected server is not answereing to a request.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.31;
