### ISSUE TITLE
confusing message if custom server (NIS) is not reachable

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#7]
0.1.19.b444

When I add a custom server which is not online at the time it is added, a message is displayed "Checking unconfirmed transactions..." for a pretty long time and then "Failed to get unconfirmed transactions" which I can quit with "OK". This is a strange behavior. It should say something like "Waiting for NIS...".

**Comment by kmiliak** [comment]
Can you please explain what do you mean under strange behavior?

**Comment by fyahfox** [comment]
Well maybe I should not call it "strange behavior" but "confusing wording". Clear what I mean now?

**Comment by am4n0w4r** [comment]
Resolved in 0.1.24, it now says "waiting for NIS" on requests.
