### ISSUE TITLE
Edit servers -> weird line break

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#70]
v0.1.27.b1956

![edit-servers-linebreak](https://cloud.githubusercontent.com/assets/6625264/12167359/06f52aac-b52c-11e5-9d3a-e41aea6eab2e.jpg)
the linebreak is weird. it should be after "http://" not in between the 2 dashes^^

**Comment by am4n0w4r** [comment]
I removed protocol and port displaying if they are default, to free some space. Also removed the second line, it shouldn't be there, it's a bug. Also added ellipsizing (...) for long server names, same as with address. In 0.1.29;

**Comment by fyahfox** [comment]
nice, good ideas!
how can you read the complete host or ip if too long?
