### ISSUE TITLE
add "display private key" at "export account" screen

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#71]
see here: https://github.com/NewEconomyMovement/NEMiOSApp/issues/61

**Comment by am4n0w4r** [comment]
Added in 0.1.28;

**Comment by fyahfox** [comment]
Nice, looks pretty good already.
Minor enhancement:
- Please make the parts "full control over the associated funds and assets" and "keep it top secret" in dark red.
- And please add paragraphs (break) between each sentence for better readability.

**Comment by fyahfox** [comment]
I just noticed that the iOs app also displays the public key at the export screen. That is pretty neat actually. Is it possible to do that for Android as well?

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30;

**Comment by fyahfox** [comment]
Ok, it now displays the pub key, but only after I display the priv key.
iOS displays the pub key immediately, without the need to display the priv key.

The thing is: The pub key is no security issue, but the priv key is of course. So if a user wants to get the pub key for any reason he now has to take the unneeded risk and display the pirv key for that. So, can you plese do it like iOS?

Generally, please always also look at the iOS version, we want the apps to be as similar as possible...

**Comment by am4n0w4r** [comment]
Fixed in 0.1.31
