### ISSUE TITLE
language settings buggy

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#74]
0.1.28.b2003

the language settings contains 3 languages total: 2 which i cant read and "Device default".
my device default is german, so why is "english" not in that list?

also: when i chose "device default", it still displays "Deutsch" when i go back to options... but that is wrong because there is no "Deutsch" yet and the app is in english...

**Comment by am4n0w4r** [comment]
Resolved in 0.1.29, now app falls back to English if unsupported default locale set;
