### ISSUE TITLE
Add lines in between transactions on Dashboard. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#75]
In my original mock-ups in the app report, I had grey lines separating the transactions on Dashboard. Not sure if it is easy to add those or not, but it would look better.  Here is a mock-up.  

Basically little grey lines in the same style as the More menu. 

![image](https://cloud.githubusercontent.com/assets/10395907/12377904/7582b434-bd70-11e5-9dd6-20f894f46f8f.png)

**Comment by jabo38** [comment]
Please see https://github.com/NewEconomyMovement/NEMiOSApp/issues/69 for collaboration with iOS dev as the two apps are different.

**Comment by am4n0w4r** [comment]
There was a bug with list background on some phones, dashboard should look like on this screenshot, fixed in 0.1.30
![screen-dashboard](https://cloud.githubusercontent.com/assets/7976963/12428247/3dd39a76-beec-11e5-8a29-c27a4270ef2e.jpg)
