### ISSUE TITLE
Adding 12 and 24 hour options to notifications 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#76]
Some people will maybe only need their app to check every 12 or 24 hours too.  

![image](https://cloud.githubusercontent.com/assets/10395907/12377915/19dd9c24-bd71-11e5-95a2-acbf44069c14.png)

Here is the iOS issue. 
https://github.com/NewEconomyMovement/NEMiOSApp/issues/70

**Comment by fyahfox** [comment]
again, it is important to have the same settings as iOs has...

**Comment by am4n0w4r** [comment]
Resolved in 0.1.29;
