### ISSUE TITLE
Making names in address book appear instead of account numbers 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#77]
When somebody has a contact added to address book, we should see that name through the different app panels instead of account addresses.  

![image](https://cloud.githubusercontent.com/assets/10395907/12378006/f13ab40c-bd73-11e5-828a-ad7ca034e8ca.png)

**Comment by am4n0w4r** [comment]
Resolved, 0.1.29;

**Comment by jabo38** [comment]
fixed
