### ISSUE TITLE
Searching in dashboard through different transactions. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#78]
When I am in the iOS app I can pull down and get a search bar.  As I type, it filters the names of the different people I have had transactions with.  

![image](https://cloud.githubusercontent.com/assets/10395907/12378016/3d81870a-bd74-11e5-868b-7c0c5b70c110.png)

![image](https://cloud.githubusercontent.com/assets/10395907/12378017/420e501e-bd74-11e5-8080-9e7a336d64a6.png)

**Comment by fyahfox** [comment]
I don't like the fact that search is displayed via pull down. Becaue usually "pull down" is refresh, and we should implement this for the Dashboard as well sometime in the future.

Any better idea how to display search textbox?

**Comment by fyahfox** [comment]
i added the mustfix label, because at least we have to make both apps look similar.

so please start to discuss it and help us find a good way how to do it in both apps.

**Comment by jabo38** [comment]
I talked this over.  In light that the API doesn't have a lot of content to search anyway, search doesn't make sense right now, so no search on Android and we will remove it from iOS
