### ISSUE TITLE
Android can not scan iOS invoices or iOS address book entries

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#79]
Android can scan iOS export account QRs - yes
iOS can scan Android export account QRs - yes
Android can scan iOS invoices - no
iOS can scan Android invoices - yes
Android can scan iOS address book entries - no
iOS can scan Android address book entries - yes

linked issue https://github.com/NewEconomyMovement/NEMiOSApp/issues/75

**Comment by jabo38** [comment]
testing the new version of Android 1.29 and iOS 2.12.  It seems like iOS can make and scan fine.  

Android can make QRs fine for iOS, but Android can't scan anything correctly.

**Comment by am4n0w4r** [comment]
Please test this in 0.1.30, fixed weird bug in QR scanner that was due to inconsistent and undocumented Android realizations.
