### ISSUE TITLE
"Host" textbox at "Select Server" doesn't handle illegal inputs

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#8]
0.1.19.b444

"Host" textbox at "Select Server" (custom NIS) allows not allowed chars (e.g. @) and there is zero logic to check if that is a host at all. For example it accepts "102" as a host. Please block illegal characters at least. If possible make a basic check if the input text is a host (for example contains at least one period).

**Comment by am4n0w4r** [comment]
Fixed in 0.1.20, added hostname validation with support for international domain names.

**Comment by fyahfox** [comment]
Ok, it is better (e.g. it says "invalid hostname" if you have illegal chars in the hostname like "@" or "+" or something like that), but it still allows "102" as a host. Also 102.42 or 102.42.14 etc. So it is not the best host vlidation I have ever seen^^

**Comment by am4n0w4r** [comment]
Well, according to [RFC1123, chapter 2.1](http://tools.ietf.org/html/rfc1123#section-6.1.3.2), all of these including "102" as numeric single-level name are valid hostnames:
> If a dotted-decimal number can be entered without such
           identifying delimiters, then a full syntactic check must be
           made, _because a segment of a host domain name is now allowed
           to begin with a digit and could legally be entirely numeric_
           (see Section 6.1.2.4).  However, a valid host name can never
           have the dotted-decimal form #.#.#.#, since at least the
           highest-level component label will be alphabetic.

**Comment by fyahfox** [comment]
Well, I didn't know "102" is a valid host^^

**Comment by am4n0w4r** [comment]
Agree, looks strange as a hostname...

**Comment by am4n0w4r** [comment]
Resolved.

**Comment by fyahfox** [comment]
I can still add "102", it will then appear as
http://102:7890

**Comment by am4n0w4r** [comment]
I'll try to explain this.
Technically there is validation for that input - try to enter app$.com or go%ogle.com - it will fail.
Although it's not common in the Internet, 123.45, or 102.42, or 123.45.67 are valid hostnames according to specifications, it's like google.com or web.example.com, but just numeric.
Just 123 (no dots at all) is valid hostname too and it may be used for example in some private networks.
If you agree with this, I guess we can close this issue, But if you think this should not be accepted, please provide names or patterns that should be considered invalid

**Comment by fyahfox** [comment]
Ah right, I didn't think about hostnames on local networks. Thanks for the clarification!
