### ISSUE TITLE
Message text should be copyable

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#82]
0.1.29

It should be possible to copy a message (both in- and outbound) with the default long press functionality.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30;

**Comment by fyahfox** [comment]
nice, thanks!

**Comment by fyahfox** [comment]
this doesnt work anymore in 1.0.41

**Comment by am4n0w4r** [comment]
Fixed in 1.0.43;
