### ISSUE TITLE
3rd line of long accout names is cut off

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#83]
0.1.29

If an account name is so long that it uses 3 lines, the 3rd line is cut off:
![photo_2016-01-19_19-43-04](https://cloud.githubusercontent.com/assets/6625264/12428454/e32c559c-bee4-11e5-8ca6-21deda4cfb27.jpg)

It should either be 2 lines and then shortened with "..." or something, or 3 lines and then shortened (if even longer). But 2 lines and a cut off 3rd line is not nice.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30;

**Comment by fyahfox** [comment]
Thanks, it is now shortened correctly.

Is there any way to view the full name in the app though?

**Comment by fyahfox** [comment]
hm by editing the name, anything else?

**Comment by am4n0w4r** [comment]
Edit name, and in My Info view, above QR code

**Comment by fyahfox** [comment]
right, ok. its not perfect, but i guess good enough for now.
