### ISSUE TITLE
displaying of decimal places

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#88]
0.1.30

Again, please don't make two different apps, but always the same, if OS is not restricting it...

So for this example, the best option would be:
Only display those decimal places that exist.
Example:
504 XEM
252.1 XEM
23957.0001 XEM
0.000001 XEM

etc

![photo_2016-01-23_14-30-39](https://cloud.githubusercontent.com/assets/6625264/12530377/e2b31bea-c1dd-11e5-8157-3f4b1d0a4af3.jpg)

![photo_2016-01-23_14-30-22](https://cloud.githubusercontent.com/assets/6625264/12530378/ecc271e4-c1dd-11e5-8bc7-2ae70d874a7b.jpg)

**Comment by jabo38** [comment]
Here are some more screens and more explanation.  

https://github.com/NewEconomyMovement/NEMiOSApp/issues/95

**Comment by am4n0w4r** [comment]
resolved in 0.1.31;
