### ISSUE TITLE
New transaction -> dropdown menu for multisig accounts: always display address/label

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#89]
0.1.30

When an account is cosigner of other accounts and you create a new transaction, you can pick other account to initiage the transaction (https://github.com/NewEconomyMovement/NEMAndroidApp/issues/80#issuecomment-173899307).

Now, it is of course needed to not display public keys in that dropdown list, but addresses or labels, if address is in address book.

Generally: Alwas display addresses if label unknown. Pub keys are never needed, expect very few special cases, which we covered already I think.

**Comment by am4n0w4r** [comment]
Changed public key display in 0.1.31;

**Comment by fyahfox** [comment]
Ok, it now displayes the address. It's a little hard to display the label, because I cannot copy the address in that dropdown menu and (and this cant stay like that:) I cannot see the complete address. I think you should just make it go over 2 lines in such case. It is important to be able to check the complete address in case of doubt. Also you could increase the distance between the items in this dropdown menu, or/and even add a line as separator. It is really hard to pick the address on the small screen.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.32;
You can import cosig as app account, and then export/scan info to address book.

**Comment by fyahfox** [comment]
I don't have the private key of the cosigner, so that is not an option.
Adding the address manually to the address book doesn't work either (https://github.com/NewEconomyMovement/NEMAndroidApp/issues/119), so I cannot test this.

**Comment by fyahfox** [comment]
i could finally test with 0.1.35 and it works -> confirmed fixed
