### ISSUE TITLE
If keyboard is displayed: Hide icon bar (Dashboard/Address Book/QR/More)

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#90]
0.1.30

When the keyboard is displayed, it should cover the icon bar, because there is not enough space left if both is displayed.
Just do it like iOS, please.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/12536453/d2efa834-c2e8-11e5-92f5-52e3b9474b0b.png)

**Comment by am4n0w4r** [comment]
Resolved in 0.1.31, changed keyboard behavior and added Next/Done action buttons for smoother navigation;

**Comment by fyahfox** [comment]
Can you explain what exactly you mean with Next/Done action buttons?

**Comment by jabo38** [comment]
works well on my phone.  We have next/done buttons on iphone.  It basically is like and "enter" button where if you press next, it moves you to the next blank.  If you it done, it closes the keyboard.

**Comment by fyahfox** [comment]
Hm, I use Swiftkey instead of original android keyboard, so maybe that is why I don't see a Next or Done button. I do have a enter button though and that does indeed bring me to the next textbox. So if you just mean this, yes that works.

**Comment by fyahfox** [comment]
-> https://github.com/NewEconomyMovement/NEMAndroidApp/issues/56
