### ISSUE TITLE
Strange number keyboard (does not have "." or ",")

### ISSUE THREAD

**Issue by Pinhais** [NewEconomyMovement/NEMAndroidApp#93]
Hi there guys!

I have a problem here with my Zenphone 2 android 5.0 standard brazilian portuguese keyboard:

When I click over some received value, here:

![value received](https://cloud.githubusercontent.com/assets/7996344/12598492/c6c3d988-c471-11e5-9342-04e59be91af4.jpg)

And I click to send some money, this keyboard is show to me:

![numero_teclado](https://cloud.githubusercontent.com/assets/7996344/12598519/eed4ceaa-c471-11e5-80aa-d430c1c95ff9.jpg)

When I click over the message, my default keyboard is this one here (normal over any kind of application on my cell):

![message keyboard](https://cloud.githubusercontent.com/assets/7996344/12598558/1aaa3772-c472-11e5-8caf-5ea917d2cda8.jpg)

I dont have any kind of optimisation over the android keyboard. It is on Brazilian portuguese (default as the first day I've turned on my phone first time.)

This should be an international keyboard problem.

As result, I cant send any kind of non int value like 0.000001.

I just can send some non int value if I write it on message area, copy and paste it at the value inputbox.

Thanks a lot

**Comment by fyahfox** [comment]
It is also a problem at iOS, and iirc they fixed it by using the numeric part of the alphabetical keyboard instead of the "full numeric keyboard". Sorry, if the terms are confusing, I don't know how to describe it better.

This is what I mean: (maybe you are able to force this keyboard mode?)

![oum5y](https://cloud.githubusercontent.com/assets/6625264/12598922/a61c7ed0-c48d-11e5-8cc2-6cd3bef74acd.png)

**Comment by Pinhais** [comment]
Brazilian Money notation, as curiosity is:

R$ 1.000,00
. is the thousand separator
, is the decimal separator

And no. I cant change the numeric keyboard which is shown to me. It depends on the java programation inside app.

the code is something like this(for android):

editText.setRawInputType(Configuration.KEYBOARD_QWERTY);

**Comment by fyahfox** [comment]
Oh sorry, I meant the dev, not you ;)
You cant change the keyboard type, it has to be coded in another way to make it display ;)

**Comment by am4n0w4r** [comment]
Resolved this by setting input type to text. This is a hack but it seems this is the only way that will work across different devices and keyboards. 0.1.32;

**Comment by lcharles123** [comment]
I think we could go back with the numeric keypad, on my phone, for example, the keyboard has keys "." and ",". https://i.imgur.com/2bCxKbu.jpg
Not much importance the value after the decimal point for now, it may be important when the XEM reach $1 or more. :)

**Comment by fyahfox** [comment]
Well, it should still be possible to use a decimal point, so the hack should stay.

I was waiting for @Pinhais to confirm this fixed, then I can close the issue...
