### ISSUE TITLE
Crash while changing password

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#95]
0.1.31

The app just crashed while I was trying to change the app password.
This should be fixed, because it is a sensible feature.

**Comment by am4n0w4r** [comment]
When exactly did the crash happen?

**Comment by fyahfox** [comment]
few minutes before i created the issue

**Comment by am4n0w4r** [comment]
Ok, thanks, I'll look into reporter.
After what event this happened? Were you opening the popup, entering some of passwords, or after pressing Confirm, etc?

**Comment by fyahfox** [comment]
I played around with it a little bit. Entering wrong old password, then correct but too short new password etc.
Then finally did a valid change (correct old password, long enough and matching new passwords), hit OK -> crash

**Comment by am4n0w4r** [comment]
And how many accounts were in the app when it crashed?

**Comment by fyahfox** [comment]
Hmm, not sure. I think 4. Why does that matter?

**Comment by am4n0w4r** [comment]
The app needs to reencrypt accounts with new password, so it could be related.
Changed mechanism a bit, and added more specific logging. Please test in 0.1.34;

**Comment by fyahfox** [comment]
Thanks!
So you think the more accounts somebody is using the more likely the app crashes?

**Comment by am4n0w4r** [comment]
Theoretically, yes

**Comment by fyahfox** [comment]
0.1.34

it seems i cant reproduce it any more.

one more thing though: why do i have to enter the password again, after chaning it, and then going back to the account list?
couldn't it auto login with the new password? i mean, user just entered that...
