### ISSUE TITLE
conversation view: unconfirmed TXes disappear instead of being displayed with confirmed TXes

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#97]
0.1.31

When I send multiple transactions, they get listed as unconfirmed (which is fine of course). After some time I send another transaction, and then the older unconfirmed transactions disappeared from unconfirmed list (which is fine of course) but didnt appear in normal (confirmed) list.

**Comment by am4n0w4r** [comment]
Did this happen while you didn't move to another app screen between sending transactions? Because when conversation opens, it takes update from server for both confirmed/unconfirmed transactions and there are displayed as is.
Fixed, now all transactions are updated after send, in 0.1.32;

**Comment by fyahfox** [comment]
"Did this happen while you didn't move to another app screen between sending transactions?" yes

ok, lets see in 0.1.32 :) thx
