### ISSUE TITLE
App goes back to primary account although this is not wanted

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#98]
0.1.31

To reproduce the error:
- Have 2 accounts in the wallet.
- Set one account as primary.
- Go to the non-primary account inside conversation view (not dashboard but inside an actual transaction)
- Now use back button -> App is now in Dashboard of primary account, but it should be in Dashboard if the account that I just used.

**Comment by am4n0w4r** [comment]
Fixed in 0.1.32;
