### ISSUE TITLE
Amount of "conversations" in Dashboard limited?

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#99]
0.1.31

It seems that the amount of conversations in the Dashboard is limited. At least I can see only 8 conversations in the Dashboard of one of my accounts, but with NCC I see a lot more addresses that account had transactions with.

Can you clarify what happens here?

**Comment by am4n0w4r** [comment]
Same as in iOS here, we take last transactions from server (it returns max 25) and then group them by conversations and show the newest message

**Comment by gimer** [comment]
ok, but you can query for more....

**Comment by fyahfox** [comment]
Please request 2x 25 when loading the dashboard (asynchronously of course, we might increase the amount later) and then load more once user scrolls to a limit (case a: conversation scrolled to bottom; case b: inside a conversation transactions scrolled to top).

**Comment by am4n0w4r** [comment]
Commented [here](https://github.com/NewEconomyMovement/NEMiOSApp/issues/100)

**Comment by fyahfox** [comment]
Ok, we are aware that there is no guarantee, but we think it is still better to have 50 than 25 as long as we don't have the perfect solution with the improved API calls.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.38;
